### PR TITLE
Fix OMPT build problem when OpenMP is enabled

### PR DESCRIPTION
**Pull request by albestro**
## Problem
I'm trying to build APEX with GCC (via spack) and when I enable OpenMP support I get a building error due to a missing include.

```bash
[98%] Building CXX object src/apex/CMakeFiles/apex_ompt.dir/apex_ompt.cpp.o
cd /tmp/ialberto/spack-stage/spack-stage-apex-2.6.3-xjsydnhb2xprb5al3pk6xk5gyk6azatr/spack-src/spack-build-hid37to/src/apex && /project/csstaff/
/tmp/ialberto/spack-stage/spack-stage-apex-2.6.3-xjsydnhb2xprb5al3pk6xk5gyk6azatr/spack-src/src/apex/apex_ompt.cpp:10:10: fatal error: omp-tools
   10 | #include <omp-tools.h>
      |          ^~~~~~~~~~~~~
```

## Quick fix
I had a quick look at it, and I have a quick fix for my use-case.

Since `OMP_INCLUDE_DIRS` is set by `FindOMPT` in any case OMPT is found,

https://github.com/UO-OACISS/apex/blob/0cc0ac985e39e80242e45c80099bd7538fab45e3/cmake/Modules/FindOMPT.cmake#L118-L123

I propose to add unconditionally the include directories to the target `apex_ompt` as per this PR.

## Notes

1. From my basic understanding, the following global `include_directories` directive can be removed

https://github.com/UO-OACISS/apex/blob/0cc0ac985e39e80242e45c80099bd7538fab45e3/src/apex/CMakeLists_standalone.cmake#L118

2. I'm not sure if this change, if correct, should be applied somehow also to `src/apex/CMakeLists_hpx.cmake`.

3. I'm going to open a PR also in spack about this. Depending on the outcome of this PR, I would add a conflict or a patch to the spack package.

4. Side note: `FindOMPT` (and probably it is not alone) installs the OMPT as external project in installation path instead of the build folder. If a user set `CMAKE_INSTALL_PREFIX` (like spack does, but it might be also set to the classic `/usr/local/apex`), the installation folder will get also OMPT sources and libraries, which I'm not sure it is needed. But this might be a topic for a different issue/PR.

### CODE REVIEW

**Comment by khuck** [comment]
Thanks for reporting this... the real problem is that GCC doesn't support OMPT, and this is kind of a hacky work-around. It is more reasonable going forward to _not_ build the LLVM OpenMP library for use with GCC, because as it is currently integrated it doesn't support target offload, and is several years out of date.

**Comment by albestro** [comment]
Yep, it makes sense. 

Would you like to just close and discard this PR without any further change? Probably better to address this on the CMake side explicitly checking and alerting that GCC does not support OMPT?

**Comment by khuck** [comment]
I won't discard it, I'll keep it to remind me to disable that configuration combination. Thanks!

**Comment by khuck** [comment]
Resolved with aa25fd3 which disables the APEX_BUILD_OMPT feature.

**Pull request closed without merging**
